(() => {
  'use strict';
  const state = { balance: 1000, bet: 10, active: false, player: [], dealer: [] };
  const session = { rounds: 0, wins: 0, losses: 0, wagered: 0, returned: 0, history: [] };
  const $ = id => document.getElementById(id);
  const money = value => '$' + value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  const values = { A: 11, K: 10, Q: 10, J: 10 };
  const el = { balance: $('balanceValue'), mini: $('miniBalance'), bet: $('betInput'), liveBet: $('liveBet'), payout: $('livePayout'), net: $('sessionNet'), status: $('panelStatus'), roundStatus: $('roundStatus'), primary: $('primaryBtn'), hit: $('hitBtn'), stand: $('standBtn'), player: $('playerHand'), dealer: $('dealerHand'), playerScore: $('playerScore'), dealerScore: $('dealerScore'), playerReadout: $('playerReadout'), dealerReadout: $('dealerReadout'), hint: $('hintText'), rounds: $('sessionRounds'), wins: $('sessionWins'), losses: $('sessionLosses'), history: $('history'), count: $('historyCount'), modal: $('resultModal') };
  function cardValue(card) { return values[card.rank] || Number(card.rank); }
  function score(hand) { let total = hand.reduce((sum, card) => sum + cardValue(card), 0); let aces = hand.filter(card => card.rank === 'A').length; while (total > 21 && aces) { total -= 10; aces -= 1; } return total; }
  function makeCard() { const ranks = ['A', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K']; const suits = ['♠', '♥', '♦', '♣']; const rank = ranks[Math.floor(Math.random() * ranks.length)]; return { rank, suit: suits[Math.floor(Math.random() * suits.length)] }; }
  function renderHand(container, hand, hidden = false) { container.innerHTML = hand.map((card, index) => `<div class="playing-card ${hidden && index === 0 ? 'hidden-card' : card.suit === '♥' || card.suit === '♦' ? 'red-card' : ''}"><span>${hidden && index === 0 ? '?' : card.rank}</span><b>${hidden && index === 0 ? 'N' : card.suit}</b></div>`).join(''); }
  function update() { const playerScore = score(state.player); const dealerScore = score(state.dealer); el.balance.textContent = money(state.balance); el.mini.textContent = money(state.balance) + ' available'; el.liveBet.textContent = money(state.bet); el.payout.textContent = state.active ? money(state.bet * 1.5) : '$0.00'; el.playerScore.textContent = state.player.length ? playerScore : '0'; el.dealerScore.textContent = state.active ? '?' : state.dealer.length ? dealerScore : '0'; el.playerReadout.textContent = state.player.length ? playerScore : '—'; el.dealerReadout.textContent = state.active ? '?' : state.dealer.length ? dealerScore : '—'; el.rounds.textContent = session.rounds; el.wins.textContent = session.wins; el.losses.textContent = session.losses; const net = session.returned - session.wagered; el.net.textContent = (net >= 0 ? '+' : '−') + money(Math.abs(net)); }
  function setHint(text, type = '') { el.hint.textContent = text; el.hint.className = `hint ${type}`; }
  function render() { renderHand(el.player, state.player); renderHand(el.dealer, state.dealer, state.active); update(); }
  function setActions(locked) { el.hit.disabled = locked; el.stand.disabled = locked; el.bet.disabled = locked; [...document.querySelectorAll('.quick-bets button'), $('betStepUp'), $('betStepDown')].forEach(button => { button.disabled = locked; }); }
  function startRound() { if (state.active) return; const bet = Number.parseFloat(el.bet.value); if (!Number.isFinite(bet) || bet <= 0) return setHint('Enter a valid bet amount first.', 'lose'); if (bet > state.balance) return setHint('That bet is more than your available balance.', 'lose'); state.bet = Math.round(bet * 100) / 100; state.balance -= state.bet; state.player = [makeCard(), makeCard()]; state.dealer = [makeCard(), makeCard()]; state.active = true; session.wagered += state.bet; el.status.textContent = 'LIVE'; el.roundStatus.textContent = 'LIVE'; el.primary.disabled = true; el.primary.querySelector('span').textContent = 'In hand'; setActions(true); el.hit.disabled = false; el.stand.disabled = false; render(); setHint('Hit for another card or stand on your hand.'); if (score(state.player) === 21) finish('blackjack'); }
  function hit() { if (!state.active) return; state.player.push(makeCard()); render(); if (score(state.player) > 21) finish('loss'); else if (score(state.player) === 21) stand(); }
  function stand() { if (!state.active) return; while (score(state.dealer) < 17) state.dealer.push(makeCard()); const playerScore = score(state.player); const dealerScore = score(state.dealer); finish(playerScore > dealerScore ? 'win' : playerScore === dealerScore ? 'push' : 'loss'); }
  function finish(result) { state.active = false; const playerScore = score(state.player); const dealerScore = score(state.dealer); const payout = result === 'blackjack' ? state.bet * 2.5 : result === 'win' ? state.bet * 2 : result === 'push' ? state.bet : 0; state.balance += payout; if (result === 'win' || result === 'blackjack') { session.wins += 1; session.returned += payout; } else if (result === 'push') { session.returned += payout; } else session.losses += 1; session.rounds += 1; session.history.unshift({ bet: state.bet, player: playerScore, dealer: dealerScore, result: result.toUpperCase(), payout }); session.history = session.history.slice(0, 10); setActions(false); el.hit.disabled = true; el.stand.disabled = true; el.primary.disabled = false; el.primary.querySelector('span').textContent = 'New hand'; el.status.textContent = result === 'loss' ? 'BUSTED' : 'COMPLETE'; el.roundStatus.textContent = result === 'loss' ? 'BUSTED' : 'COMPLETE'; render(); setHint(result === 'loss' ? 'The dealer takes this hand.' : result === 'push' ? 'A push. Your bet returns.' : `You locked ${money(payout)}.`, result === 'loss' ? 'lose' : 'win'); renderHistory(); showResult(result, payout); }
  function renderHistory() { el.count.textContent = `${session.history.length} / 10`; el.history.innerHTML = session.history.length ? '<div class="history-row"><span>Bet</span><span>Hand</span><span>Result</span><span>Payout</span></div>' + session.history.map(item => `<div class="history-row"><strong>${money(item.bet)}</strong><span>${item.player} / ${item.dealer}</span><span class="${item.result === 'LOSS' ? 'loss' : 'win'}">${item.result}</span><strong class="${item.result === 'LOSS' ? 'loss' : 'win'}">${item.payout ? '+' + money(item.payout) : '−' + money(item.bet)}</strong></div>`).join('') : '<div class="empty-history">Your completed hands will appear here.</div>'; }
  function showResult(result, payout) { $('resultIcon').textContent = result === 'loss' ? '×' : result === 'push' ? '—' : '$'; $('resultKicker').textContent = result === 'blackjack' ? 'BLACKJACK' : result === 'push' ? 'PUSH' : result === 'win' ? 'HAND WON' : 'HAND LOST'; $('resultTitle').textContent = result === 'loss' ? 'Dealer wins' : result === 'push' ? 'It is a push' : 'You won'; $('resultAmount').textContent = result === 'loss' ? '−' + money(state.bet) : result === 'push' ? money(payout) : '+' + money(payout); $('resultAmount').style.color = result === 'loss' ? 'var(--red)' : result === 'push' ? 'var(--gold)' : 'var(--green)'; $('resultBody').textContent = `Your hand ${score(state.player)} · Dealer hand ${score(state.dealer)}.`; $('resultDetail').textContent = `${money(state.bet)} bet · ${result.toLowerCase()}`; el.modal.classList.remove('hidden'); }
  function resetRound() { state.active = false; state.player = []; state.dealer = []; el.primary.disabled = false; el.primary.querySelector('span').textContent = 'Deal hand'; el.status.textContent = 'READY'; el.roundStatus.textContent = 'READY'; setHint('Place a bet, then play your hand.'); render(); }
  el.primary.addEventListener('click', () => state.active ? null : startRound()); el.hit.addEventListener('click', hit); el.stand.addEventListener('click', stand); $('playAgain').addEventListener('click', () => { el.modal.classList.add('hidden'); resetRound(); el.primary.focus(); }); $('modalClose').addEventListener('click', () => el.modal.classList.add('hidden')); el.modal.addEventListener('click', event => { if (event.target === el.modal) el.modal.classList.add('hidden'); });
  $('betQuick').addEventListener('click', event => { const button = event.target.closest('button'); if (!button || state.active) return; const current = Number.parseFloat(el.bet.value) || state.bet; const value = button.dataset.action === 'max' ? state.balance : button.dataset.action === 'double' ? current * 2 : current / 2; el.bet.value = Math.min(state.balance, Math.max(.01, value)).toFixed(2); }); $('betStepUp').addEventListener('click', () => { if (!state.active) el.bet.value = (Number(el.bet.value) + 1).toFixed(2); }); $('betStepDown').addEventListener('click', () => { if (!state.active) el.bet.value = Math.max(.01, Number(el.bet.value) - 1).toFixed(2); }); el.bet.addEventListener('input', () => { el.bet.value = el.bet.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1'); });
  const settingsModal = $('settingsModal'); $('settingsBtn').addEventListener('click', () => settingsModal.classList.remove('hidden')); $('settingsClose').addEventListener('click', () => settingsModal.classList.add('hidden')); settingsModal.addEventListener('click', event => { if (event.target === settingsModal) settingsModal.classList.add('hidden'); }); $('resetBalance').addEventListener('click', () => { if (!state.active) { state.balance = 1000; update(); } }); document.addEventListener('keydown', event => { if (event.key === 'Escape') { el.modal.classList.add('hidden'); settingsModal.classList.add('hidden'); } });
  resetRound(); renderHistory(); requestAnimationFrame(() => $('loadingScreen').classList.add('loaded'));
})();
