(() => {
  'use strict';

  const state = { balance: 1000, bet: 10, active: false, busy: false, multiplier: 1, safeCard: -1 };
  const session = { rounds: 0, wins: 0, losses: 0, wagered: 0, returned: 0, history: [] };
  const audio = { context: null, enabled: localStorage.getItem('nexbe-sound') !== 'off', volume: 0.65 };
  const $ = id => document.getElementById(id);
  const money = value => '$' + value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  const el = { balance: $('balanceValue'), mini: $('miniBalance'), bet: $('betInput'), liveBet: $('liveBet'), payout: $('livePayout'), net: $('sessionNet'), status: $('panelStatus'), roundStatus: $('roundStatus'), primary: $('primaryBtn'), cash: $('cashoutBtn'), cashVal: $('cashoutValue'), cashMult: $('cashoutMult'), multiplier: $('multiplierValue'), next: $('nextPayout'), cards: $('cardTable'), hint: $('hintText'), rounds: $('sessionRounds'), wins: $('sessionWins'), losses: $('sessionLosses'), history: $('history'), count: $('historyCount'), modal: $('resultModal') };

  function update() {
    const payout = state.active ? state.bet * state.multiplier : 0;
    el.balance.textContent = money(state.balance); el.mini.textContent = money(state.balance) + ' available'; el.liveBet.textContent = money(state.bet); el.payout.textContent = money(payout); el.multiplier.textContent = state.multiplier.toFixed(2) + '×'; el.next.textContent = money(state.bet * state.multiplier * 2); el.cashVal.textContent = money(payout); el.cashMult.textContent = state.multiplier.toFixed(2) + '×'; el.cash.disabled = !state.active; el.rounds.textContent = session.rounds; el.wins.textContent = session.wins; el.losses.textContent = session.losses;
    const net = session.returned - session.wagered; el.net.textContent = (net >= 0 ? '+' : '−') + money(Math.abs(net));
  }

  function setHint(text, type = '') { el.hint.textContent = text; el.hint.className = `hint ${type}`; }
  function playSound(type) { if (!audio.enabled) return; const AudioContext = window.AudioContext || window.webkitAudioContext; if (!AudioContext) return; audio.context ||= new AudioContext(); const now = audio.context.currentTime; const oscillator = audio.context.createOscillator(); const gain = audio.context.createGain(); oscillator.connect(gain); gain.connect(audio.context.destination); oscillator.type = type === 'loss' ? 'sawtooth' : 'triangle'; oscillator.frequency.setValueAtTime(type === 'loss' ? 100 : 420, now); oscillator.frequency.exponentialRampToValueAtTime(type === 'loss' ? 35 : 820, now + .2); gain.gain.setValueAtTime(.15 * audio.volume, now); gain.gain.exponentialRampToValueAtTime(.001, now + .2); oscillator.start(now); oscillator.stop(now + .2); }
  function setLocked(locked) { [...document.querySelectorAll('.quick-bets button'), $('betStepUp'), $('betStepDown')].forEach(button => { button.disabled = locked; }); el.bet.disabled = locked; }
  function resetCards() { el.cards.querySelectorAll('.flip-card').forEach(card => { card.className = 'flip-card'; card.querySelector('span').textContent = '?'; }); }
  function revealAllCards() { el.cards.querySelectorAll('.flip-card').forEach(card => { const isSafe = Number(card.dataset.card) === state.safeCard; card.classList.add('flipped', isSafe ? 'safe' : 'danger'); card.querySelector('span').textContent = isSafe ? '2×' : '×'; }); }

  function startRound() { if (state.active || state.busy) return; const bet = Number.parseFloat(el.bet.value); if (!Number.isFinite(bet) || bet <= 0) return setHint('Enter a valid bet amount first.', 'lose'); if (bet > state.balance) return setHint('That bet is more than your available balance.', 'lose'); state.bet = Math.round(bet * 100) / 100; state.balance -= state.bet; state.active = true; state.multiplier = 1; state.safeCard = Math.floor(Math.random() * 3); session.wagered += state.bet; resetCards(); el.status.textContent = 'LIVE'; el.roundStatus.textContent = 'LIVE'; el.primary.disabled = true; el.primary.querySelector('span').textContent = 'Choose a card'; setLocked(true); setHint('One card doubles your multiplier. Find it.'); update(); playSound('click'); }

  function chooseCard(event) { if (!state.active || state.busy) return; const card = event.target.closest('.flip-card'); if (!card) return; state.busy = true; const index = Number(card.dataset.card); card.classList.add('flipped'); if (index === state.safeCard) { card.classList.add('safe'); card.querySelector('span').textContent = '2×'; state.multiplier *= 2; state.busy = false; setHint(`Nice pick. You are at ${state.multiplier.toFixed(2)}×. Double again or cash out.`, 'win'); el.primary.disabled = false; el.primary.querySelector('span').textContent = 'Double again'; update(); playSound('safe'); return; } card.classList.add('danger'); card.querySelector('span').textContent = '×'; el.cards.querySelectorAll('.flip-card').forEach(item => { if (Number(item.dataset.card) === state.safeCard) { item.classList.add('flipped', 'safe'); item.querySelector('span').textContent = '2×'; } }); finish(false); }

  function finish(won, freshChoice = false) { state.active = false; state.busy = false; const payout = won ? state.bet * state.multiplier : 0; if (!won) revealAllCards(); if (won) { state.balance += payout; session.wins += 1; session.returned += payout; } else session.losses += 1; session.rounds += 1; session.history.unshift({ bet: state.bet, multiplier: won ? state.multiplier : 0, payout, result: won ? 'WIN' : 'LOSS' }); session.history = session.history.slice(0, 10); setLocked(false); el.primary.disabled = false; el.primary.querySelector('span').textContent = 'New round'; el.status.textContent = won ? 'LANDED' : 'BUSTED'; el.roundStatus.textContent = won ? 'COMPLETE' : 'BUSTED'; setHint(won ? `You locked ${money(payout)} at ${state.multiplier.toFixed(2)}×.` : 'That card was not safe. The bet is gone.', won ? 'win' : 'lose'); renderHistory(); update(); if (!freshChoice) showResult(won, payout); }

  function cashOut() { if (state.active && !state.busy && state.multiplier > 1) { state.busy = true; playSound('cashout'); finish(true); } }
  function renderHistory() { el.count.textContent = `${session.history.length} / 10`; el.history.innerHTML = session.history.length ? '<div class="history-row"><span>Bet</span><span>Result</span><span>Multiplier</span><span>Payout</span></div>' + session.history.map(item => `<div class="history-row"><strong>${money(item.bet)}</strong><span class="${item.result === 'WIN' ? 'win' : 'loss'}">${item.result}</span><span>${item.multiplier ? item.multiplier.toFixed(2) + '×' : '—'}</span><strong class="${item.result === 'WIN' ? 'win' : 'loss'}">${item.payout ? '+' + money(item.payout) : '−' + money(item.bet)}</strong></div>`).join('') : '<div class="empty-history">Your completed flips will appear here.</div>'; }
  function showResult(won, payout) { $('resultIcon').textContent = won ? '$' : '×'; $('resultKicker').textContent = won ? 'CASHED OUT' : 'ROUND OVER'; $('resultTitle').textContent = won ? 'You won' : 'Wrong card'; $('resultAmount').textContent = won ? '+' + money(payout) : '−' + money(state.bet); $('resultAmount').style.color = won ? 'var(--green)' : 'var(--red)'; $('resultBody').textContent = won ? 'Good timing. Your payout is locked in.' : 'The safe card was hiding somewhere else.'; $('resultDetail').textContent = `${money(state.bet)} bet · ${won ? state.multiplier.toFixed(2) + '× payout' : 'No return'}`; el.modal.classList.remove('hidden'); }

  el.cards.addEventListener('click', chooseCard); el.primary.addEventListener('click', () => { if (state.active && state.multiplier > 1) { state.safeCard = Math.floor(Math.random() * 3); resetCards(); state.busy = false; setHint('The deck is shuffled. Find the safe card again.'); } else startRound(); }); el.cash.addEventListener('click', cashOut); $('playAgain').addEventListener('click', () => { el.modal.classList.add('hidden'); resetRound(); el.primary.focus(); }); $('modalClose').addEventListener('click', () => el.modal.classList.add('hidden')); el.modal.addEventListener('click', event => { if (event.target === el.modal) el.modal.classList.add('hidden'); });
  function resetRound() { state.active = false; state.busy = false; state.multiplier = 1; state.safeCard = -1; resetCards(); el.status.textContent = 'READY'; el.roundStatus.textContent = 'READY'; el.primary.disabled = false; el.primary.querySelector('span').textContent = 'Place bet'; setLocked(false); setHint('Place your bet, then choose a card.'); update(); }
  $('betQuick').addEventListener('click', event => { const button = event.target.closest('button'); if (!button || state.active) return; const current = Number.parseFloat(el.bet.value) || state.bet; const value = button.dataset.action === 'max' ? state.balance : button.dataset.action === 'double' ? current * 2 : current / 2; el.bet.value = Math.min(state.balance, Math.max(.01, value)).toFixed(2); playSound('click'); }); $('betStepUp').addEventListener('click', () => { if (!state.active) el.bet.value = (Number(el.bet.value) + 1).toFixed(2); }); $('betStepDown').addEventListener('click', () => { if (!state.active) el.bet.value = Math.max(.01, Number(el.bet.value) - 1).toFixed(2); }); el.bet.addEventListener('input', () => { el.bet.value = el.bet.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1'); });
  const soundButton = $('soundBtn'); const settingsModal = $('settingsModal'); const syncSound = () => { soundButton.setAttribute('aria-pressed', audio.enabled); soundButton.textContent = audio.enabled ? '◉' : '◖'; }; syncSound(); soundButton.addEventListener('click', () => { audio.enabled = !audio.enabled; localStorage.setItem('nexbe-sound', audio.enabled ? 'on' : 'off'); syncSound(); }); $('settingsBtn').addEventListener('click', () => settingsModal.classList.remove('hidden')); $('settingsClose').addEventListener('click', () => settingsModal.classList.add('hidden')); settingsModal.addEventListener('click', event => { if (event.target === settingsModal) settingsModal.classList.add('hidden'); }); $('volumeInput').addEventListener('input', event => { audio.volume = Number(event.target.value); }); $('resetBalance').addEventListener('click', () => { if (!state.active) { state.balance = 1000; update(); } }); document.addEventListener('keydown', event => { if (event.key === 'Escape') { el.modal.classList.add('hidden'); settingsModal.classList.add('hidden'); } });
  resetRound(); renderHistory(); requestAnimationFrame(() => $('loadingScreen').classList.add('loaded'));
})();
