(() => {
  'use strict';
  const ROWS = 10;
  const multipliers = [8, 4, 2, 1, .5, .25, .5, 1, 2, 4, 8];
  const state = { balance: 1000, bet: 10, active: false, inFlight: 0, drops: 0 };
  const session = { rounds: 0, wins: 0, losses: 0, wagered: 0, returned: 0, history: [] };
  const audio = { context: null, enabled: localStorage.getItem('nexbe-sound') !== 'off', volume: .65 };
  const $ = id => document.getElementById(id);
  const money = value => '$' + value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  const el = { balance: $('balanceValue'), mini: $('miniBalance'), bet: $('betInput'), liveBet: $('liveBet'), payout: $('livePayout'), net: $('sessionNet'), status: $('panelStatus'), roundStatus: $('roundStatus'), primary: $('primaryBtn'), ball: $('plinkoBall'), board: $('plinkoBoard'), slots: $('plinkoSlots'), landing: $('landingValue'), drops: $('dropCount'), hint: $('hintText'), rounds: $('sessionRounds'), wins: $('sessionWins'), losses: $('sessionLosses'), history: $('history'), count: $('historyCount') };
  function makeBoard() { el.board.innerHTML = ''; for (let row = 0; row < ROWS; row += 1) { const line = document.createElement('div'); line.className = 'plinko-row'; for (let peg = 0; peg <= row; peg += 1) { const dot = document.createElement('i'); dot.className = 'plinko-peg'; line.appendChild(dot); } el.board.appendChild(line); } el.slots.innerHTML = multipliers.map((value, index) => `<div class="plinko-slot slot-${index}">${value}×</div>`).join(''); }
  function update() { el.balance.textContent = money(state.balance); el.mini.textContent = money(state.balance) + ' available'; el.liveBet.textContent = money(state.bet); el.drops.textContent = state.drops; el.rounds.textContent = session.rounds; el.wins.textContent = session.wins; el.losses.textContent = session.losses; const net = session.returned - session.wagered; el.net.textContent = (net >= 0 ? '+' : '−') + money(Math.abs(net)); }
  function setHint(text, type = '') { el.hint.textContent = text; el.hint.className = `hint ${type}`; }
  function sound(type) { if (!audio.enabled) return; const AudioContext = window.AudioContext || window.webkitAudioContext; if (!AudioContext) return; audio.context ||= new AudioContext(); const now = audio.context.currentTime; const oscillator = audio.context.createOscillator(); const gain = audio.context.createGain(); oscillator.connect(gain); gain.connect(audio.context.destination); oscillator.type = type === 'land' ? 'triangle' : 'sine'; oscillator.frequency.setValueAtTime(type === 'land' ? 260 : 520, now); oscillator.frequency.exponentialRampToValueAtTime(type === 'land' ? 620 : 260, now + .12); gain.gain.setValueAtTime(.12 * audio.volume, now); gain.gain.exponentialRampToValueAtTime(.001, now + .12); oscillator.start(now); oscillator.stop(now + .12); }
  function setLocked(locked) { el.bet.disabled = locked; [...document.querySelectorAll('.quick-bets button'), $('betStepUp'), $('betStepDown')].forEach(button => { button.disabled = locked; }); }
  function animateBall(slot, bet) { const boardWidth = el.board.clientWidth || 500; const boardLeft = el.board.offsetLeft; const boardTop = el.board.offsetTop; const boardHeight = el.board.clientHeight || 320; const ball = el.ball.cloneNode(true); ball.removeAttribute('id'); ball.classList.remove('hidden'); el.ball.parentElement.appendChild(ball); const startX = boardLeft + boardWidth / 2; const slotX = boardLeft + ((slot + .5) / multipliers.length) * boardWidth; ball.style.left = `${startX}px`; ball.style.top = `${boardTop}px`; const path = []; let x = startX; for (let row = 0; row < ROWS; row += 1) { const progress = row / ROWS; const edgeInset = progress * boardWidth / 2; const leftEdge = boardLeft + edgeInset + 10; const rightEdge = boardLeft + boardWidth - edgeInset - 10; x += (Math.random() > .5 ? 1 : -1) * boardWidth / 16; x = Math.max(leftEdge, Math.min(rightEdge, x)); path.push({ x, y: boardTop + progress * boardHeight }); } path.push({ x: slotX, y: boardTop + boardHeight + 28 }); let step = 0; const move = () => { if (step >= path.length) return land(slot, ball, bet); const point = path[step]; ball.style.left = `${point.x}px`; ball.style.top = `${point.y}px`; sound('peg'); step += 1; window.setTimeout(move, 105); }; move(); }
  function land(slot, ball, bet) { ball.style.left = `${((slot + .5) / multipliers.length) * 100}%`; ball.style.top = 'calc(100% - 25px)'; window.setTimeout(() => ball.remove(), 350); const value = multipliers[slot]; const payout = bet * value; state.balance += payout; session.returned += payout; session.rounds += 1; if (value >= 1) session.wins += 1; else session.losses += 1; session.history.unshift({ bet, multiplier: value, payout, result: value >= 1 ? 'WIN' : 'LOSS' }); session.history = session.history.slice(0, 10); state.inFlight -= 1; el.slots.querySelectorAll('.plinko-slot').forEach(item => item.classList.remove('landed')); el.slots.children[slot].classList.add('landed'); el.landing.textContent = `${value}×`; el.status.textContent = state.inFlight ? 'DROPPING' : 'COMPLETE'; el.roundStatus.textContent = state.inFlight ? `${state.inFlight} LIVE` : 'COMPLETE'; state.active = state.inFlight > 0; setHint(value >= 1 ? `The ball landed on ${value}×. You won ${money(payout)}.` : `The ball landed on ${value}×. Try another drop.`, value >= 1 ? 'win' : 'lose'); sound('land'); renderHistory(); update(); }
  function drop() { const bet = Number.parseFloat(el.bet.value); if (!Number.isFinite(bet) || bet <= 0) return setHint('Enter a valid bet amount first.', 'lose'); if (bet > state.balance) return setHint('That bet is more than your available balance.', 'lose'); state.bet = Math.round(bet * 100) / 100; state.balance -= state.bet; session.wagered += state.bet; state.active = true; state.inFlight += 1; state.drops += 1; el.status.textContent = 'DROPPING'; el.roundStatus.textContent = `${state.inFlight} LIVE`; el.primary.disabled = false; el.primary.querySelector('span').textContent = 'Drop another'; setHint('Drop another ball whenever you like.'); update(); animateBall(Math.floor(Math.random() * multipliers.length), state.bet); }
  function renderHistory() { el.count.textContent = `${session.history.length} / 10`; el.history.innerHTML = session.history.length ? '<div class="history-row"><span>Bet</span><span>Result</span><span>Multiplier</span><span>Payout</span></div>' + session.history.map(item => `<div class="history-row"><strong>${money(item.bet)}</strong><span class="${item.result === 'WIN' ? 'win' : 'loss'}">${item.result}</span><span>${item.multiplier.toFixed(2)}×</span><strong class="${item.result === 'WIN' ? 'win' : 'loss'}">${item.payout ? '+' + money(item.payout) : '−' + money(item.bet)}</strong></div>`).join('') : '<div class="empty-history">Your completed drops will appear here.</div>'; }
  el.primary.addEventListener('click', drop); $('betQuick').addEventListener('click', event => { const button = event.target.closest('button'); if (!button || state.active) return; const current = Number.parseFloat(el.bet.value) || state.bet; const value = button.dataset.action === 'max' ? state.balance : button.dataset.action === 'double' ? current * 2 : current / 2; el.bet.value = Math.min(state.balance, Math.max(.01, value)).toFixed(2); }); $('betStepUp').addEventListener('click', () => { if (!state.active) el.bet.value = (Number(el.bet.value) + 1).toFixed(2); }); $('betStepDown').addEventListener('click', () => { if (!state.active) el.bet.value = Math.max(.01, Number(el.bet.value) - 1).toFixed(2); }); el.bet.addEventListener('input', () => { el.bet.value = el.bet.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1'); });
  const settingsModal = $('settingsModal'); const soundButton = $('soundBtn'); soundButton.addEventListener('click', () => { audio.enabled = !audio.enabled; localStorage.setItem('nexbe-sound', audio.enabled ? 'on' : 'off'); soundButton.textContent = audio.enabled ? '◉' : '◖'; }); $('settingsBtn').addEventListener('click', () => settingsModal.classList.remove('hidden')); $('settingsClose').addEventListener('click', () => settingsModal.classList.add('hidden')); settingsModal.addEventListener('click', event => { if (event.target === settingsModal) settingsModal.classList.add('hidden'); }); $('volumeInput').addEventListener('input', event => { audio.volume = Number(event.target.value); }); $('resetBalance').addEventListener('click', () => { if (!state.active) { state.balance = 1000; update(); } });
  makeBoard(); update(); renderHistory(); requestAnimationFrame(() => $('loadingScreen').classList.add('loaded'));
})();
