(() => {
  'use strict';
  const state = { balance: 1000, bet: 10, selectedBet: 10, active: false, player: [], bots: [], community: [], revealed: 0, pot: 0, toCall: 0, raiseUsed: false, resolving: false };
  const session = { rounds: 0, wins: 0, losses: 0, wagered: 0, returned: 0, history: [] };
  const $ = id => document.getElementById(id);
  const money = value => '$' + value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  const suits = ['♠', '♥', '♦', '♣'];
  const ranks = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A'];
  const value = rank => ranks.indexOf(rank) + 2;
  const el = { balance: $('balanceValue'), mini: $('miniBalance'), bet: $('betInput'), slider: $('betSlider'), sliderValue: $('betSliderValue'), sliderLimit: $('betSliderLimit'), liveBet: $('liveBet'), payout: $('livePayout'), net: $('sessionNet'), status: $('roundStatus'), round: $('roundStatus'), primary: $('primaryBtn'), check: $('callBtn'), call: $('callActionBtn'), raise: $('raiseBtn'), fold: $('foldBtn'), player: $('playerHand'), community: $('communityCards'), pot: $('potValue'), potReadout: $('potReadout'), handReadout: $('handReadout'), street: $('streetLabel'), hint: $('hintText'), rounds: $('sessionRounds'), wins: $('sessionWins'), losses: $('sessionLosses'), history: $('history'), count: $('historyCount'), modal: $('resultModal'), playerStatus: $('playerStatus'), playerStack: $('playerStack'), playerBet: $('playerBet') };
  const names = ['Axel', 'Blaze', 'Cora'];
  function deck() { return suits.flatMap(suit => ranks.map(rank => ({ suit, rank }))).sort(() => Math.random() - .5); }
  function cardText(card) { return `${card.rank}${card.suit}`; }
  function renderCard(card, hidden = false) { return `<div class="playing-card ${hidden ? 'card-back' : card.suit === '♥' || card.suit === '♦' ? 'red-card' : ''}"><span>${hidden ? '?' : card.rank}</span><b>${hidden ? 'N' : card.suit}</b></div>`; }
  function chipMoney(value) { return '$' + Math.round(value).toLocaleString(); }
  function updateSeatMetrics() { const ids = ['One', 'Two', 'Three']; el.playerStack.textContent = chipMoney(state.balance); el.playerBet.textContent = chipMoney(state.player.length ? state.bet : 0) + ' in'; el.playerStatus.textContent = state.resolving ? 'Showdown' : state.active ? 'Your turn' : state.player.length ? 'Complete' : 'Waiting'; ids.forEach(id => { $(`bot${id}Stack`).textContent = '$1,000'; $(`bot${id}Bet`).textContent = '$0 in'; }); state.bots.forEach((bot, index) => { const id = ids[index]; $(`bot${id}Stack`).textContent = chipMoney(bot.stack); $(`bot${id}Bet`).textContent = chipMoney(bot.bet) + ' in'; }); }
  function setSelectedBet(rawValue) { const minimum = state.active ? state.bet + state.toCall : .01; const maximum = Math.max(minimum, state.active ? state.balance + state.bet : state.balance); const next = Math.min(maximum, Math.max(minimum, Number.parseFloat(rawValue) || minimum)); state.selectedBet = Math.round(next * 100) / 100; el.bet.value = state.selectedBet.toFixed(2); el.slider.min = minimum.toFixed(2); el.slider.max = maximum.toFixed(2); el.slider.value = state.selectedBet; el.sliderValue.textContent = 'Bet: ' + money(state.selectedBet); el.sliderLimit.textContent = 'Up to ' + money(maximum); }
  function update() { const net = session.returned - session.wagered; el.balance.textContent = money(state.balance); el.mini.textContent = money(state.balance) + ' available'; el.liveBet.textContent = money(state.bet); el.payout.textContent = state.active ? money(state.pot) : '$0.00'; el.rounds.textContent = session.rounds; el.wins.textContent = session.wins; el.losses.textContent = session.losses; el.net.textContent = (net >= 0 ? '+' : '−') + money(Math.abs(net)); setSelectedBet(state.selectedBet); updateSeatMetrics(); }
  function render() { const visibleCards = state.active ? state.community.slice(0, state.revealed) : state.community; el.player.innerHTML = state.player.map(card => renderCard(card)).join(''); el.community.innerHTML = visibleCards.map(card => renderCard(card)).join(''); el.pot.textContent = money(state.pot); el.potReadout.textContent = money(state.pot); el.handReadout.textContent = state.player.length ? state.player.map(cardText).join(' ') : '—'; update(); }
  function setHint(text, type = '') { el.hint.textContent = text; el.hint.className = `hint ${type}`; }
  const handNames = ['High card', 'Pair', 'Two pair', 'Three of a kind', 'Straight', 'Flush', 'Full house', 'Four of a kind', 'Straight flush'];
  function compareScores(left, right) { for (let index = 0; index < left.length; index += 1) if (left[index] !== right[index]) return left[index] > right[index] ? 1 : -1; return 0; }
  function evaluateFive(cards) { const values = cards.map(card => value(card.rank)).sort((a, b) => b - a); const counts = new Map(); cards.forEach(card => counts.set(value(card.rank), (counts.get(value(card.rank)) || 0) + 1)); const groups = [...counts.entries()].sort((left, right) => right[1] - left[1] || right[0] - left[0]); const flush = cards.every(card => card.suit === cards[0].suit); const unique = [...new Set(values)]; let straightHigh = 0; if (unique.length === 5 && unique[0] - unique[4] === 4) straightHigh = unique[0]; if (unique.join(',') === '14,5,4,3,2') straightHigh = 5; if (straightHigh && flush) return [8, straightHigh]; if (groups[0][1] === 4) return [7, groups[0][0], groups[1][0]]; if (groups[0][1] === 3 && groups[1][1] === 2) return [6, groups[0][0], groups[1][0]]; if (flush) return [5, ...values]; if (straightHigh) return [4, straightHigh]; if (groups[0][1] === 3) return [3, groups[0][0], ...groups.slice(1).map(group => group[0]).sort((a, b) => b - a)]; if (groups[0][1] === 2 && groups[1][1] === 2) return [2, Math.max(groups[0][0], groups[1][0]), Math.min(groups[0][0], groups[1][0]), groups[2][0]]; if (groups[0][1] === 2) return [1, groups[0][0], ...groups.slice(1).map(group => group[0]).sort((a, b) => b - a)]; return [0, ...values]; }
  function combinations(cards) { const results = []; for (let first = 0; first < cards.length - 4; first += 1) for (let second = first + 1; second < cards.length - 3; second += 1) for (let third = second + 1; third < cards.length - 2; third += 1) for (let fourth = third + 1; fourth < cards.length - 1; fourth += 1) for (let fifth = fourth + 1; fifth < cards.length; fifth += 1) results.push([cards[first], cards[second], cards[third], cards[fourth], cards[fifth]]); return results; }
  function evaluateHand(cards) { return combinations(cards).reduce((best, combo) => { const score = evaluateFive(combo); return !best || compareScores(score, best) > 0 ? score : best; }, null); }
  function handLabel(score) { return handNames[score[0]]; }
  function botStatus() { const ids = ['One', 'Two', 'Three']; state.bots.forEach((bot, index) => { const status = bot.folded ? 'Fold' : bot.action; $(`bot${ids[index]}Status`).textContent = status; $(`bot${ids[index]}Hand`).innerHTML = bot.folded ? '' : `${renderCard(bot.hand[0], state.active)}${renderCard(bot.hand[1], state.active)}`; }); }
  function deal() { if (state.active || state.resolving) return; const bet = Number.parseFloat(state.selectedBet); if (!Number.isFinite(bet) || bet <= 0) return setHint('Enter a valid buy-in first.', 'lose'); if (bet > state.balance) return setHint('That buy-in is more than your available balance.', 'lose'); const cards = deck(); state.bet = Math.round(bet * 100) / 100; state.selectedBet = state.bet; state.balance -= state.bet; session.wagered += state.bet; state.player = [cards.pop(), cards.pop()]; state.bots = names.map((name, index) => { const folded = Math.random() < .14 + index * .06; return { name, hand: [cards.pop(), cards.pop()], stack: 1000 - (folded ? 0 : state.bet), bet: folded ? 0 : state.bet, folded, action: folded ? 'Fold' : 'Check' }; }); state.community = [cards.pop(), cards.pop(), cards.pop(), cards.pop(), cards.pop()]; state.revealed = 3; state.toCall = 0; state.raiseUsed = false; state.resolving = false; state.pot = state.bet + state.bots.reduce((total, bot) => total + bot.bet, 0); state.active = true; el.status.textContent = 'LIVE'; el.round.textContent = 'FLOP'; el.primary.disabled = true; el.check.disabled = false; el.call.disabled = true; el.raise.disabled = false; el.fold.disabled = false; el.primary.querySelector('span').textContent = 'Hand in play'; el.street.textContent = 'FLOP'; render(); botStatus(); setHint('The flop is down. Check to see the turn.'); }
  function raise() { if (!state.active || state.resolving || state.raiseUsed) return; const minimumRaise = state.bet + state.toCall; const increment = state.selectedBet - state.bet; if (state.selectedBet <= minimumRaise) return setHint(`Move the slider above ${money(minimumRaise)} to re-raise.`, 'lose'); if (increment > state.balance) return setHint('You do not have enough balance to raise.', 'lose'); state.balance -= increment; session.wagered += increment; state.bet = state.selectedBet; state.bots.forEach(bot => { if (!bot.folded) { const additional = Math.max(0, state.bet - bot.bet); bot.stack -= additional; bot.bet += additional; state.pot += additional; bot.action = 'Call'; } }); state.pot += increment; state.toCall = 0; state.raiseUsed = true; el.check.disabled = false; el.call.disabled = true; el.raise.disabled = true; el.status.textContent = 'RAISE'; render(); botStatus(); setHint(`You re-raised to ${money(state.bet)}. Check to continue.`, 'win'); }
  function botRaise() { const bot = state.bots.find(candidate => !candidate.folded); if (!bot) return false; state.bots.forEach(candidate => { if (!candidate.folded) candidate.action = 'Check'; }); const increment = state.bet; bot.stack -= increment; bot.bet += increment; bot.action = 'Raise'; state.pot += increment; state.toCall = increment; el.check.disabled = true; el.call.disabled = false; el.raise.disabled = false; el.status.textContent = 'CALL'; render(); botStatus(); setHint(`${bot.name} raised ${money(increment)}. Call, re-raise, or fold.`); return true; }
  function resolve(folded = false) { state.resolving = false; const playerScore = evaluateHand([...state.player, ...state.community]); const botScores = state.bots.map(bot => bot.folded ? null : evaluateHand([...bot.hand, ...state.community])); const botBest = botScores.reduce((bestScore, score) => !score || bestScore && compareScores(bestScore, score) >= 0 ? bestScore : score, null); const best = folded ? null : [playerScore, ...botScores.filter(Boolean)].reduce((bestScore, score) => !bestScore || compareScores(score, bestScore) > 0 ? score : bestScore, null); const winners = folded ? [] : [playerScore, ...botScores].map((score, index) => score && compareScores(score, best) === 0 ? index : -1).filter(index => index >= 0); const playerWins = winners.includes(0) && winners.length === 1; const tie = winners.includes(0) && winners.length > 1; const winningBotIndex = folded ? botScores.findIndex(score => score && compareScores(score, botBest) === 0) + 1 : winners.find(index => index > 0); const winningBot = winningBotIndex >= 1 ? state.bots[winningBotIndex - 1] : null; const winningScore = winningBotIndex >= 1 ? botScores[winningBotIndex - 1] : null; const winningRank = winningScore ? handLabel(winningScore) : 'the best hand'; const payout = playerWins ? state.pot : tie ? state.pot / winners.length : 0; state.balance += payout; session.returned += payout; if (playerWins) session.wins += 1; else if (!tie) session.losses += 1; session.rounds += 1; session.history.unshift({ bet: state.bet, result: playerWins ? 'WIN' : tie ? 'PUSH' : 'LOSS', payout }); session.history = session.history.slice(0, 10); state.active = false; state.toCall = 0; state.revealed = 5; el.check.disabled = true; el.call.disabled = true; el.raise.disabled = true; el.fold.disabled = true; el.primary.disabled = false; el.primary.querySelector('span').textContent = 'Deal table'; el.status.textContent = playerWins ? 'WIN' : tie ? 'PUSH' : 'LOST'; el.round.textContent = 'COMPLETE'; render(); botStatus(); setHint(playerWins ? `You took the ${money(state.pot)} pot.` : tie ? 'Split pot. Your hand tied at showdown.' : folded ? 'You folded. The hand is over.' : 'The bots took the pot.', playerWins || tie ? 'win' : 'lose'); renderHistory(); showResult(playerWins, tie, payout, handLabel(playerScore), winningBot?.name || 'The table', winningRank, folded); }
  function call() { if (!state.active || state.resolving || !state.toCall) return; if (state.toCall > state.balance) return setHint('You do not have enough chips to call.', 'lose'); state.balance -= state.toCall; session.wagered += state.toCall; state.bet += state.toCall; state.pot += state.toCall; state.bots.forEach(bot => { if (bot.action === 'Raise') bot.action = 'Call'; }); state.toCall = 0; el.check.disabled = false; el.call.disabled = true; el.raise.disabled = state.raiseUsed; el.street.textContent = 'RIVER'; el.round.textContent = 'RIVER'; state.revealed = 5; render(); botStatus(); setHint('Call accepted. Check to reach showdown.'); }
  function check() { if (!state.active || state.resolving || state.toCall) return; if (state.revealed === 3) { state.revealed = 4; el.street.textContent = 'TURN'; el.round.textContent = 'TURN'; render(); setHint('Check accepted. The turn is down.'); return; } if (state.revealed === 4 && botRaise()) return; if (state.revealed === 4) { state.revealed = 5; el.street.textContent = 'RIVER'; el.round.textContent = 'RIVER'; render(); setHint('Check accepted. The river is down.'); return; } state.resolving = true; el.check.disabled = true; el.call.disabled = true; el.raise.disabled = true; el.fold.disabled = true; render(); setHint('Checks are complete. Reading the table…'); window.setTimeout(() => resolve(), 450); }
  function fold() { if (!state.active || state.resolving) return; resolve(true); }
  function renderHistory() { el.count.textContent = `${session.history.length} / 10`; el.history.innerHTML = session.history.length ? '<div class="history-row"><span>Buy-in</span><span>Result</span><span>Payout</span><span>Status</span></div>' + session.history.map(item => `<div class="history-row"><strong>${money(item.bet)}</strong><span class="${item.result === 'LOSS' ? 'loss' : 'win'}">${item.result}</span><strong class="${item.result === 'LOSS' ? 'loss' : 'win'}">${item.payout ? '+' + money(item.payout) : '−' + money(item.bet)}</strong><span>${item.result === 'WIN' ? 'Pot won' : item.result === 'PUSH' ? 'Split' : 'Folded'}</span></div>`).join('') : '<div class="empty-history">Your completed hands will appear here.</div>'; }
  function showResult(win, tie, payout, rank, winnerName, winnerRank, folded) { $('resultIcon').textContent = win ? '♠' : tie ? '—' : '×'; $('resultTitle').textContent = win ? 'Pot won' : tie ? 'Split pot' : 'Bots win'; $('resultAmount').textContent = win ? '+' + money(payout) : tie ? money(payout) : '−' + money(state.bet); $('resultAmount').style.color = win ? 'var(--green)' : tie ? 'var(--gold)' : 'var(--red)'; $('resultBody').textContent = win ? 'Your hand held up at showdown.' : tie ? `${winnerName} tied your ${rank}.` : folded ? `You folded. ${winnerName} had ${winnerRank}.` : `${winnerName} won with ${winnerRank}; your ${rank} was weaker.`; $('resultDetail').textContent = `${money(state.bet)} buy-in · ${winnerName}: ${winnerRank} · You: ${rank}`; el.modal.classList.remove('hidden'); }
  function reset() { state.active = false; state.player = []; state.bots = []; state.community = []; state.revealed = 0; state.pot = 0; state.toCall = 0; state.raiseUsed = false; state.resolving = false; state.selectedBet = Number.parseFloat(el.bet.value) || 10; el.primary.disabled = false; el.check.disabled = true; el.call.disabled = true; el.raise.disabled = true; el.fold.disabled = true; el.primary.querySelector('span').textContent = 'Deal table'; el.status.textContent = 'READY'; el.round.textContent = 'READY'; el.street.textContent = 'PRE-FLOP'; ['One', 'Two', 'Three'].forEach(id => { $(`bot${id}Status`).textContent = 'Waiting'; $(`bot${id}Hand`).innerHTML = ''; }); render(); setHint('Deal a table and play against three bots.'); }
  el.primary.addEventListener('click', deal); el.check.addEventListener('click', check); el.call.addEventListener('click', call); el.raise.addEventListener('click', raise); el.fold.addEventListener('click', fold); $('playAgain').addEventListener('click', () => { el.modal.classList.add('hidden'); reset(); el.primary.focus(); }); $('modalClose').addEventListener('click', () => { el.modal.classList.add('hidden'); reset(); }); el.modal.addEventListener('click', event => { if (event.target === el.modal) { el.modal.classList.add('hidden'); reset(); } });
  $('betQuick').addEventListener('click', event => { const button = event.target.closest('button'); if (!button || state.resolving) return; const pot = state.pot || state.bet; const action = button.dataset.action; const next = action === 'half-pot' ? pot / 2 : action === 'pot' ? pot : action === 'double-pot' ? pot * 2 : state.active ? state.balance + state.bet : state.balance; setSelectedBet(next); }); el.slider.addEventListener('input', event => setSelectedBet(event.target.value)); $('betStepUp').addEventListener('click', () => { if (!state.active) setSelectedBet(Number(el.bet.value) + 1); }); $('betStepDown').addEventListener('click', () => { if (!state.active) setSelectedBet(Number(el.bet.value) - 1); }); el.bet.addEventListener('input', () => { el.bet.value = el.bet.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1'); if (!state.active) setSelectedBet(el.bet.value); });
  const settingsModal = $('settingsModal'); $('settingsBtn').addEventListener('click', () => settingsModal.classList.remove('hidden')); $('settingsClose').addEventListener('click', () => settingsModal.classList.add('hidden')); settingsModal.addEventListener('click', event => { if (event.target === settingsModal) settingsModal.classList.add('hidden'); }); $('resetBalance').addEventListener('click', () => { if (!state.active) { state.balance = 1000; update(); } }); document.addEventListener('keydown', event => { if (event.key === 'Escape') { el.modal.classList.add('hidden'); settingsModal.classList.add('hidden'); } });
  reset(); renderHistory(); requestAnimationFrame(() => $('loadingScreen').classList.add('loaded'));
})();
