(() => {
  'use strict';
  const state = { balance: 1000, bet: 10, active: false, player: [], bots: [], community: [], pot: 0 };
  const session = { rounds: 0, wins: 0, losses: 0, wagered: 0, returned: 0, history: [] };
  const $ = id => document.getElementById(id);
  const money = value => '$' + value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  const suits = ['♠', '♥', '♦', '♣'];
  const ranks = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A'];
  const value = rank => ranks.indexOf(rank) + 2;
  const el = { balance: $('balanceValue'), mini: $('miniBalance'), bet: $('betInput'), liveBet: $('liveBet'), payout: $('livePayout'), net: $('sessionNet'), status: $('roundStatus'), round: $('roundStatus'), primary: $('primaryBtn'), call: $('callBtn'), fold: $('foldBtn'), player: $('playerHand'), community: $('communityCards'), pot: $('potValue'), potReadout: $('potReadout'), handReadout: $('handReadout'), street: $('streetLabel'), hint: $('hintText'), rounds: $('sessionRounds'), wins: $('sessionWins'), losses: $('sessionLosses'), history: $('history'), count: $('historyCount'), modal: $('resultModal') };
  const names = ['Axel', 'Blaze', 'Cora'];
  function deck() { return suits.flatMap(suit => ranks.map(rank => ({ suit, rank }))).sort(() => Math.random() - .5); }
  function cardText(card) { return `${card.rank}${card.suit}`; }
  function renderCard(card, hidden = false) { return `<div class="playing-card ${hidden ? 'card-back' : card.suit === '♥' || card.suit === '♦' ? 'red-card' : ''}"><span>${hidden ? '?' : card.rank}</span><b>${hidden ? 'N' : card.suit}</b></div>`; }
  function update() { const net = session.returned - session.wagered; el.balance.textContent = money(state.balance); el.mini.textContent = money(state.balance) + ' available'; el.liveBet.textContent = money(state.bet); el.payout.textContent = state.active ? money(state.pot) : '$0.00'; el.rounds.textContent = session.rounds; el.wins.textContent = session.wins; el.losses.textContent = session.losses; el.net.textContent = (net >= 0 ? '+' : '−') + money(Math.abs(net)); }
  function render() { const visibleCards = state.active ? state.community.slice(0, 3) : state.community; el.player.innerHTML = state.player.map(card => renderCard(card)).join(''); el.community.innerHTML = visibleCards.map(card => renderCard(card)).join(''); el.pot.textContent = money(state.pot); el.potReadout.textContent = money(state.pot); el.handReadout.textContent = state.player.length ? state.player.map(cardText).join(' ') : '—'; update(); }
  function setHint(text, type = '') { el.hint.textContent = text; el.hint.className = `hint ${type}`; }
  function handRank(cards) { const counts = new Map(); cards.forEach(card => counts.set(card.rank, (counts.get(card.rank) || 0) + 1)); const values = [...new Set(cards.map(card => value(card.rank)))].sort((a, b) => b - a); let straight = 0; for (let i = 0; i <= values.length - 5; i += 1) if (values[i] - values[i + 4] === 4) straight = values[i]; if (values.includes(14) && values.includes(2) && values.includes(3) && values.includes(4) && values.includes(5)) straight = Math.max(straight, 5); const groups = [...counts.values()].sort((a, b) => b - a); const flush = suits.some(suit => cards.filter(card => card.suit === suit).length >= 5); if (straight && flush) return 8; if (groups[0] === 4) return 7; if (groups[0] === 3 && groups[1] >= 2) return 6; if (flush) return 5; if (straight) return 4; if (groups[0] === 3) return 3; if (groups[0] === 2 && groups[1] === 2) return 2; if (groups[0] === 2) return 1; return 0; }
  function botStatus() { const ids = ['One', 'Two', 'Three']; state.bots.forEach((bot, index) => { const status = bot.folded ? 'Folded' : 'In'; $(`bot${ids[index]}Status`).textContent = status; $(`bot${ids[index]}Hand`).innerHTML = bot.folded ? '' : `${renderCard(bot.hand[0], true)}${renderCard(bot.hand[1], true)}`; }); }
  function deal() { if (state.active) return; const bet = Number.parseFloat(el.bet.value); if (!Number.isFinite(bet) || bet <= 0) return setHint('Enter a valid buy-in first.', 'lose'); if (bet > state.balance) return setHint('That buy-in is more than your available balance.', 'lose'); const cards = deck(); state.bet = Math.round(bet * 100) / 100; state.balance -= state.bet; session.wagered += state.bet; state.player = [cards.pop(), cards.pop()]; state.bots = names.map((name, index) => ({ name, hand: [cards.pop(), cards.pop()], folded: Math.random() < .14 + index * .06 })); state.community = [cards.pop(), cards.pop(), cards.pop(), cards.pop(), cards.pop()]; state.pot = state.bet * (1 + state.bots.filter(bot => !bot.folded).length); state.active = true; el.status.textContent = 'LIVE'; el.round.textContent = 'FLOP'; el.primary.disabled = true; el.call.disabled = false; el.fold.disabled = false; el.primary.querySelector('span').textContent = 'Hand in play'; el.street.textContent = 'FLOP'; render(); botStatus(); setHint('The bots are in. Call to see the board and reach showdown.'); }
  function resolve(folded = false) { const playerRank = handRank([...state.player, ...state.community]); const botRanks = state.bots.map(bot => bot.folded ? -1 : handRank([...bot.hand, ...state.community])); const best = Math.max(playerRank, ...botRanks); const playerWins = !folded && playerRank === best && botRanks.filter(rank => rank === best).length === 0; const tie = !folded && playerRank === best && botRanks.filter(rank => rank === best).length > 0; const payout = playerWins ? state.pot : tie ? state.bet : 0; state.balance += payout; session.returned += payout; if (playerWins) session.wins += 1; else session.losses += 1; session.rounds += 1; session.history.unshift({ bet: state.bet, result: playerWins ? 'WIN' : tie ? 'PUSH' : 'LOSS', payout }); session.history = session.history.slice(0, 10); state.active = false; el.call.disabled = true; el.fold.disabled = true; el.primary.disabled = false; el.primary.querySelector('span').textContent = 'Deal table'; el.status.textContent = playerWins ? 'WIN' : tie ? 'PUSH' : 'LOST'; el.round.textContent = 'COMPLETE'; render(); setHint(playerWins ? `You took the ${money(state.pot)} pot.` : tie ? 'Split pot. Your buy-in returns.' : folded ? 'You folded. The hand is over.' : 'The bots took the pot.', playerWins || tie ? 'win' : 'lose'); renderHistory(); showResult(playerWins, tie, payout, playerRank); }
  function call() { if (!state.active) return; el.street.textContent = 'RIVER'; setHint('Showdown. Reading the table…'); window.setTimeout(() => resolve(), 450); }
  function fold() { if (!state.active) return; resolve(true); }
  function renderHistory() { el.count.textContent = `${session.history.length} / 10`; el.history.innerHTML = session.history.length ? '<div class="history-row"><span>Buy-in</span><span>Result</span><span>Payout</span><span>Status</span></div>' + session.history.map(item => `<div class="history-row"><strong>${money(item.bet)}</strong><span class="${item.result === 'LOSS' ? 'loss' : 'win'}">${item.result}</span><strong class="${item.result === 'LOSS' ? 'loss' : 'win'}">${item.payout ? '+' + money(item.payout) : '−' + money(item.bet)}</strong><span>${item.result === 'WIN' ? 'Pot won' : item.result === 'PUSH' ? 'Split' : 'Folded'}</span></div>`).join('') : '<div class="empty-history">Your completed hands will appear here.</div>'; }
  function showResult(win, tie, payout, rank) { $('resultIcon').textContent = win ? '♠' : tie ? '—' : '×'; $('resultTitle').textContent = win ? 'Pot won' : tie ? 'Split pot' : 'Bots win'; $('resultAmount').textContent = win ? '+' + money(payout) : tie ? money(payout) : '−' + money(state.bet); $('resultAmount').style.color = win ? 'var(--green)' : tie ? 'var(--gold)' : 'var(--red)'; $('resultBody').textContent = win ? 'Your hand held up at showdown.' : tie ? 'The table matched your hand.' : 'The table found the stronger hand.'; $('resultDetail').textContent = `${money(state.bet)} buy-in · hand rank ${rank}`; el.modal.classList.remove('hidden'); }
  function reset() { state.active = false; state.player = []; state.bots = []; state.community = []; state.pot = 0; el.primary.disabled = false; el.call.disabled = true; el.fold.disabled = true; el.primary.querySelector('span').textContent = 'Deal table'; el.status.textContent = 'READY'; el.round.textContent = 'READY'; el.street.textContent = 'PRE-FLOP'; ['One', 'Two', 'Three'].forEach(id => { $(`bot${id}Status`).textContent = 'Waiting'; $(`bot${id}Hand`).innerHTML = ''; }); render(); setHint('Deal a table and play against three bots.'); }
  el.primary.addEventListener('click', deal); el.call.addEventListener('click', call); el.fold.addEventListener('click', fold); $('playAgain').addEventListener('click', () => { el.modal.classList.add('hidden'); reset(); el.primary.focus(); }); $('modalClose').addEventListener('click', () => { el.modal.classList.add('hidden'); reset(); }); el.modal.addEventListener('click', event => { if (event.target === el.modal) { el.modal.classList.add('hidden'); reset(); } });
  $('betQuick').addEventListener('click', event => { const button = event.target.closest('button'); if (!button || state.active) return; const current = Number.parseFloat(el.bet.value) || state.bet; const next = button.dataset.action === 'max' ? state.balance : button.dataset.action === 'double' ? current * 2 : current / 2; el.bet.value = Math.min(state.balance, Math.max(.01, next)).toFixed(2); }); $('betStepUp').addEventListener('click', () => { if (!state.active) el.bet.value = (Number(el.bet.value) + 1).toFixed(2); }); $('betStepDown').addEventListener('click', () => { if (!state.active) el.bet.value = Math.max(.01, Number(el.bet.value) - 1).toFixed(2); }); el.bet.addEventListener('input', () => { el.bet.value = el.bet.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1'); });
  const settingsModal = $('settingsModal'); $('settingsBtn').addEventListener('click', () => settingsModal.classList.remove('hidden')); $('settingsClose').addEventListener('click', () => settingsModal.classList.add('hidden')); settingsModal.addEventListener('click', event => { if (event.target === settingsModal) settingsModal.classList.add('hidden'); }); $('resetBalance').addEventListener('click', () => { if (!state.active) { state.balance = 1000; update(); } }); document.addEventListener('keydown', event => { if (event.key === 'Escape') { el.modal.classList.add('hidden'); settingsModal.classList.add('hidden'); } });
  reset(); renderHistory(); requestAnimationFrame(() => $('loadingScreen').classList.add('loaded'));
})();
