(() => {
  'use strict';
  const machines = { neon: { title: 'Neon 7s', kicker: 'NEON ORIGINAL', reels: 5, symbols: ['7', '★', '♦', '◆', '7', '✦'], theme: 'neon' }, fruit: { title: 'Moon Fruit', kicker: 'MOON ORIGINAL', reels: 7, symbols: ['🍒', '🍋', '🍇', '🍉', '⭐', '🍒'], theme: 'fruit' }, cosmic: { title: 'Cosmic Gems', kicker: 'COSMIC ORIGINAL', reels: 10, symbols: ['◆', '✦', '✧', '◇', '●', '✦'], theme: 'cosmic' }, royal: { title: 'Royal House', kicker: 'ROYAL ORIGINAL', reels: 15, symbols: ['♠', '♥', '♦', '♣', 'A', 'K'], theme: 'royal' }, ocean: { title: 'Ocean Rush', kicker: 'OCEAN ORIGINAL', reels: 7, symbols: ['🐚', '🐠', '🌊', '🐬', '★', '🐚'], theme: 'ocean' }, chrome: { title: 'Chrome Club', kicker: 'CHROME ORIGINAL', reels: 10, symbols: ['◆', '7', '♣', '★', '♦', '7'], theme: 'chrome' } };
  const state = { balance: 1000, bet: 10, machine: 'neon', spinning: false };
  const session = { rounds: 0, wins: 0, losses: 0, wagered: 0, returned: 0, history: [] };
  const audio = { context: null, enabled: localStorage.getItem('nexbe-sound') !== 'off', volume: .65 };
  const $ = id => document.getElementById(id); const money = value => '$' + value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  const el = { balance: $('balanceValue'), mini: $('miniBalance'), bet: $('betInput'), liveBet: $('liveBet'), payout: $('livePayout'), net: $('sessionNet'), status: $('panelStatus'), round: $('roundStatus'), primary: $('primaryBtn'), reels: [...document.querySelectorAll('.slot-display .reel')], display: $('slotDisplay'), cabinet: $('slotCabinet'), kicker: $('machineKicker'), title: $('machineTitle'), message: $('machineMessage'), win: $('winLabel'), hint: $('hintText'), rounds: $('sessionRounds'), wins: $('sessionWins'), losses: $('sessionLosses'), history: $('history'), count: $('historyCount'), paytable: $('paytable') };
  function update() { el.balance.textContent = money(state.balance); el.mini.textContent = money(state.balance) + ' available'; el.liveBet.textContent = money(state.bet); el.rounds.textContent = session.rounds; el.wins.textContent = session.wins; el.losses.textContent = session.losses; const net = session.returned - session.wagered; el.net.textContent = (net >= 0 ? '+' : '−') + money(Math.abs(net)); }
  function setHint(text, type = '') { el.hint.textContent = text; el.hint.className = `hint ${type}`; }
  function tone(type) { if (!audio.enabled) return; const AudioContext = window.AudioContext || window.webkitAudioContext; if (!AudioContext) return; audio.context ||= new AudioContext(); const now = audio.context.currentTime; const oscillator = audio.context.createOscillator(); const gain = audio.context.createGain(); oscillator.connect(gain); gain.connect(audio.context.destination); oscillator.type = type === 'win' ? 'triangle' : 'square'; oscillator.frequency.setValueAtTime(type === 'win' ? 420 : 180, now); oscillator.frequency.exponentialRampToValueAtTime(type === 'win' ? 900 : 90, now + .16); gain.gain.setValueAtTime(.11 * audio.volume, now); gain.gain.exponentialRampToValueAtTime(.001, now + .16); oscillator.start(now); oscillator.stop(now + .16); }
  function setMachine(machine) { state.machine = machine; const config = machines[machine]; el.kicker.textContent = config.kicker; el.title.textContent = config.title; el.cabinet.className = `slot-cabinet ${config.theme}`; el.display.style.setProperty('--reel-count', config.reels); el.display.innerHTML = Array.from({ length: config.reels }, (_, index) => `<div class="reel">${config.symbols[index % config.symbols.length]}</div>`).join(''); el.reels = [...el.display.querySelectorAll('.reel')]; el.paytable.innerHTML = `<span>3 left-to-right <b>5×</b></span><span>4 left-to-right <b>7×</b></span><span>${Math.min(config.reels, 5)} matching <b>10×</b></span><span>${config.reels} ${config.title} bonus <b>20×</b></span>`; setHint(`Playing ${config.title}: ${config.reels} reels. Place your bet, then spin.`); }
  function spin() { if (state.spinning) return; const bet = Number.parseFloat(el.bet.value); if (!Number.isFinite(bet) || bet <= 0) return setHint('Enter a valid bet amount first.', 'lose'); if (bet > state.balance) return setHint('That bet is more than your available balance.', 'lose'); const config = machines[state.machine]; state.bet = Math.round(bet * 100) / 100; state.balance -= state.bet; session.wagered += state.bet; state.spinning = true; el.primary.disabled = true; el.status.textContent = 'SPINNING'; el.round.textContent = 'LIVE'; el.primary.querySelector('span').textContent = 'Spinning…'; setHint('The reels are moving.'); el.cabinet.classList.add('spinning'); tone('spin'); const result = el.reels.map(() => config.symbols[Math.floor(Math.random() * config.symbols.length)]); let ticks = 0; const timer = window.setInterval(() => { el.reels.forEach((reel, index) => { if (ticks < 15 + index * 5) reel.textContent = config.symbols[Math.floor(Math.random() * config.symbols.length)]; }); ticks += 1; if (ticks >= 25) { window.clearInterval(timer); window.setTimeout(() => finish(result, config), 240); } }, 90); update(); }
  function finish(result, config) { el.reels.forEach((reel, index) => { reel.textContent = result[index]; }); el.cabinet.classList.remove('spinning'); const first = result[0]; let consecutive = 1; while (consecutive < result.length && result[consecutive] === first) consecutive += 1; const sevens = consecutive === 6 && first === '7'; const multiplier = sevens ? 20 : consecutive === 5 ? 10 : consecutive === 4 ? 7 : consecutive === 3 ? 5 : 0; const payout = state.bet * multiplier; if (payout) { state.balance += payout; session.returned += payout; session.wins += 1; el.win.textContent = `+${money(payout)}`; setHint(`${config.title}: ${consecutive} consecutive ${first}s, ${multiplier}× win.`, 'win'); tone('win'); } else { session.losses += 1; el.win.textContent = '—'; setHint('No left-to-right match on this payline.', 'lose'); } session.rounds += 1; session.history.unshift({ bet: state.bet, result: result.join(' '), multiplier, payout }); session.history = session.history.slice(0, 10); state.spinning = false; el.primary.disabled = false; el.status.textContent = payout ? 'WIN' : 'READY'; el.round.textContent = 'COMPLETE'; el.primary.querySelector('span').textContent = 'Spin again'; renderHistory(); update(); }
  function renderHistory() { el.count.textContent = `${session.history.length} / 10`; el.history.innerHTML = session.history.length ? '<div class="history-row"><span>Bet</span><span>Line</span><span>Multiplier</span><span>Payout</span></div>' + session.history.map(item => `<div class="history-row"><strong>${money(item.bet)}</strong><span>${item.result}</span><span class="${item.multiplier ? 'win' : 'loss'}">${item.multiplier ? item.multiplier.toFixed(2) + '×' : '—'}</span><strong class="${item.multiplier ? 'win' : 'loss'}">${item.payout ? '+' + money(item.payout) : '−' + money(item.bet)}</strong></div>`).join('') : '<div class="empty-history">Your completed spins will appear here.</div>'; }
  document.querySelectorAll('.slot-machine-choice').forEach(button => button.addEventListener('click', () => { if (state.spinning) return; document.querySelectorAll('.slot-machine-choice').forEach(item => item.classList.toggle('active', item === button)); setMachine(button.dataset.machine); })); el.primary.addEventListener('click', spin); $('betQuick').addEventListener('click', event => { const button = event.target.closest('button'); if (!button || state.spinning) return; const current = Number.parseFloat(el.bet.value) || state.bet; const value = button.dataset.action === 'max' ? state.balance : button.dataset.action === 'double' ? current * 2 : current / 2; el.bet.value = Math.min(state.balance, Math.max(.01, value)).toFixed(2); }); $('betStepUp').addEventListener('click', () => { if (!state.spinning) el.bet.value = (Number(el.bet.value) + 1).toFixed(2); }); $('betStepDown').addEventListener('click', () => { if (!state.spinning) el.bet.value = Math.max(.01, Number(el.bet.value) - 1).toFixed(2); }); el.bet.addEventListener('input', () => { el.bet.value = el.bet.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1'); });
  const settingsModal = $('settingsModal'); const soundButton = $('soundBtn'); soundButton.addEventListener('click', () => { audio.enabled = !audio.enabled; localStorage.setItem('nexbe-sound', audio.enabled ? 'on' : 'off'); soundButton.textContent = audio.enabled ? '◉' : '◖'; }); $('settingsBtn').addEventListener('click', () => settingsModal.classList.remove('hidden')); $('settingsClose').addEventListener('click', () => settingsModal.classList.add('hidden')); settingsModal.addEventListener('click', event => { if (event.target === settingsModal) settingsModal.classList.add('hidden'); }); $('volumeInput').addEventListener('input', event => { audio.volume = Number(event.target.value); }); $('resetBalance').addEventListener('click', () => { if (!state.spinning) { state.balance = 1000; update(); } });
  setMachine('neon'); update(); renderHistory(); requestAnimationFrame(() => $('loadingScreen').classList.add('loaded'));
})();
